version: '3.8'

services:
#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:80" # Mapujemy port 80 z Nginx na lokalny port 3000
#    networks:
#      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_FLYWAY_URL=jdbc:mysql://mysql:3306/devdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge