name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout kod źródłowy
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Budowanie obrazu Dockera
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/topolski-cms-frontend:latest ./frontend

      # Push obrazu do Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/topolski-cms-frontend:latest

      # Instalacja Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Deploy na Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=build

  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout kod źródłowy
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/topolski-cms-backend:latest ./backend

      # 4. Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/topolski-cms-backend:latest

      # 5. Trigger redeployment on Render
      - name: Trigger redeployment on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # Render API Key
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            ${{ secrets.RENDER_DEPLOY_HOOK }}